lesson-1-task-1
AmeliaKotlowska/invoicing-system-amelia-kotlowska pull request #2
Opened 2023-02-14 16:38 UTC by AmeliaKotlowska

2023-02-16 19:42 UTC, patryk-stepniak requested changes
Trochę mało.
Brakuje:
1. testów dla klasy App
2. gradle/wrapper/gradle-wrapper.properties
3. konfiguracji Checkstyler'a.

2023-02-16 19:50 UTC, AmeliaKotlowska commented
zapomniałam dodać w intelij już robię

2023-02-16 20:37 UTC, Julka235 approved these changes

2023-02-17 08:16 UTC, marwis1995 approved these changes

2023-02-20 23:36 UTC, merged